theme: jekyll-theme-minimal
title: Manav Khandhar
#logo: 
description: Welcome to my portfolio! I'm a Data Analyst & this is my world where I showcase what I have worked on in the past and all my experiences working with data.
