theme: jekyll-theme-minimal
title: Manav Khandhar
logo: images/1686085136348.jpg
description: Welcome to my portfolio! I'm a Data Analyst & this is my world where I showcase what I have worked on in the past and all my experiences working with data.

Tools - MSSQL, Jupyter Notebook, BigQuery, Visual Studio Code, Tableau, Looker Studio, and PowerBI

Skills - ETL (Extract, Transform, Load) Processes, Database Querying, Data Manipulation, Data Analysis, Reporting, Data Visualization, Statistical Analysis, Business Intelligence, Project Management.

Languages - SQL, Python, Google Query Language
